### PR TITLE
Minor bug fix for incorrectly named schema variable

### PR DESCRIPTION
**Pull request by shanesoh**
`access_token_header_as_bearer` seems to be incorrectly named. As a result configuring the "access token header as bearer" parameter in the oidc plugin has no effect on the plugin's behaviour.

It seems like the variable should be named `access_token_as_bearer` instead as referenced `kong/plugins/oidc/utils.lua`.

### CODE REVIEW

**Comment by damigarcia** [comment]
./README.md should also be updated with the schema parameter.
Thank you for your fix!

**Comment by shanesoh** [comment]
Done! :+1:

**Comment by daverck** [comment]
You missed renaming access_token_header_as_bearer in README.md line 227

**Comment by cristichiru** [comment]
Fixed, thanks @daverck

**Pull request merged**
