### PR TITLE
Add scope validation for jwt tokens

### PR DESCRIPTION
**Pull request by StianHaugland1**
Add scope validation for JWT tokens

### CODE REVIEW

**Comment by cristichiru** [comment]
Somehow I've missed this.. .so sorry.

**Comment by StianHaugland1** [comment]
@cristichiru No worries, when is next release? 😄

**Comment by cristichiru** [comment]
Well, I guess I should do a release as well.

FYI, this plugin is used in [revomatico/docker-kong-oidc](https://github.com/revomatico/docker-kong-oidc) using a "manual" installation step. That package has been already updated with this fix.

Looking in a container based on image release [2.7.0-2](https://github.com/revomatico/docker-kong-oidc/releases/tag/2.7.0-2), your changes are there:
```yaml
bash-5.1$ grep scope /usr/local/share/lua/5.1/kong/plugins/oidc/*
/usr/local/share/lua/5.1/kong/plugins/oidc/handler.lua:      if oidcConfig.validate_scope == "yes" then
/usr/local/share/lua/5.1/kong/plugins/oidc/handler.lua:        for scope in res.scope:gmatch("([^ ]+)")  do
/usr/local/share/lua/5.1/kong/plugins/oidc/handler.lua:          if scope == oidcConfig.scope then
/usr/local/share/lua/5.1/kong/plugins/oidc/handler.lua:          utils.exit(ngx.HTTP_FORBIDDEN,"Invalid scope",ngx.HTTP_FORBIDDEN)
/usr/local/share/lua/5.1/kong/plugins/oidc/schema.lua:    scope = { type = "string", required = true, default = "openid" },
/usr/local/share/lua/5.1/kong/plugins/oidc/schema.lua:    validate_scope = { type = "string", required = true, default = "no" },
/usr/local/share/lua/5.1/kong/plugins/oidc/utils.lua:    scope = config.scope,
/usr/local/share/lua/5.1/kong/plugins/oidc/utils.lua:    validate_scope = config.validate_scope,
```

**Comment by cristichiru** [comment]
Released: https://github.com/revomatico/kong-oidc/releases/tag/v1.2.4-1

**Pull request merged**
